### ISSUE TITLE
Assign a license

### ISSUE THREAD

**Issue by mckaydavis** [CodeWithAloha/logo#1]
As @jongeyer designed the logo, he needs to assign a license to it.

**Comment by billymeinke** [comment]
@jongeyer Let me know if I can assist with open licenses.

**Comment by mckaydavis** [comment]
To do this, the file should be called `LICENSE.md` and checked into the root directory of this repository.  

Creative Commons Markdown files can be found here: https://github.com/idleberg/Creative-Commons-Markdown

**Comment by jongeyer** [comment]
@billymeinke thanks for the help...

I think the CC BY-NC 4.0 would make sense. Can you confirm it's compatible with CC BY 3.0 (license of the shaka symbol)?

**Comment by billymeinke** [comment]
@jongeyer should be compatible.

Can you also add an attribution line to your license.txt file that has info
and a link to the CC BY shaka symbol? Title, Author, Link, License

On Wed, Feb 17, 2016 at 10:49 AM, Jon Geyer notifications@github.com
wrote:

> @billymeinke https://github.com/billymeinke thanks for the help...
> 
> I think the CC BY-NC 4.0 would make sense. Can you confirm it's compatible
> with CC BY 3.0 (license of the shaka symbol)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CodeforHawaii/logo/issues/1#issuecomment-185397126.

## 

Billy Meinke, MEd
@billymeinke https://twitter.com/billymeinke / Web
http://billymeinke.github.io

**Comment by jongeyer** [comment]
@billymeinke yes, will do. thanks

**Comment by jongeyer** [comment]
License assigned. Closing.
